### ISSUE TITLE
Update bump.sh link

### ISSUE THREAD

**Issue by overflw** [aeon-data-requests/open-data-rights-api#1]
Hey @leinelissen
I love your work! While browsing through the docs I found this defunct link: https://bump.sh/doc/open-dsar-api at the page: https://whitepaper.open-data-rights.org/proposal/api-formatting. Is it possible to fix this easily?

All the best
flow

**Comment by leinelissen** [comment]
Great catch! I changed this at some point in time to https://api.open-data-rights.org, but I have apparently missed some mentions. I'll try and do a quick Search + Replace so everything is up-to-date :)

**Comment by overflw** [comment]
Thanks!
